export default {
    // 所有的对象属性必须添加在root节点下（防止和非公共组件的状态属性重复，重复会导致覆盖）
    root : {

        // 打开的tab历史记录
        historyTabs : [],

        // 面包屑信息
        crumbsInfo:[],

        //账号管理数据
        accountManagement:[
        {
            "id":"201701",
            'index':0,
            "user":"gaohanwei1",
            "realName":"XXX",
            "section":"人力资源",
            "role":"普通管理员",
            "state":"可用",
            "joinDate":"2017-01-01"
        },
        {
            "id":"201701",
            'index':1,
            "user":"gaohanwei1",
            "realName":"XXX",
            "section":"人力",
            "role":"普通",
            "state":"可用",
            "joinDate":"2017-01-01"
        },
        {
            "id":"201",
            'index':2,
            "user":"gaohanwei1",
            "realName":"XXX",
            "section":"人力",
            "role":"普通",
            "state":"可用",
            "joinDate":"2017-01-01"
        },
            {
                "id":"201701",
                'index':3,
                "user":"gaohanwei1",
                "realName":"XXX",
                "section":"人力资源",
                "role":"普通管理员",
                "state":"可用",
                "joinDate":"2017-01-01"
            },
            {
                "id":"201701",
                'index':4,
                "user":"gaohanwei1",
                "realName":"XXX",
                "section":"人力",
                "role":"普通",
                "state":"可用",
                "joinDate":"2017-01-01"
            },
            {
                "id":"201",
                'index':5,
                "user":"gaohanwei1",
                "realName":"XXX",
                "section":"人力",
                "role":"普通",
                "state":"可用",
                "joinDate":"2017-01-01"
            },
            {
                "id":"201701",
                'index':6,
                "user":"gaohanwei1",
                "realName":"XXX",
                "section":"人力资源",
                "role":"普通管理员",
                "state":"可用",
                "joinDate":"2017-01-01"
            },
            {
                "id":"201701",
                'index':7,
                "user":"gaohanwei1",
                "realName":"XXX",
                "section":"人力",
                "role":"普通",
                "state":"可用",
                "joinDate":"2017-01-01"
            },
            {
                "id":"201",
                'index':8,
                "user":"gaohanwei1",
                "realName":"XXX",
                "section":"人力",
                "role":"普通",
                "state":"可用",
                "joinDate":"2017-01-01"
            },
            {
                "id":"201701",
                'index':9,
                "user":"gaohanwei1",
                "realName":"XXX",
                "section":"人力资源",
                "role":"普通管理员",
                "state":"可用",
                "joinDate":"2017-01-01"
            },
            {
                "id":"201701",
                'index':10,
                "user":"gaohanwei1",
                "realName":"XXX",
                "section":"人力",
                "role":"普通",
                "state":"可用",
                "joinDate":"2017-01-01"
            },
            {
                "id":"201",
                'index':11,
                "user":"gaohanwei1",
                "realName":"XXX",
                "section":"人力",
                "role":"普通",
                "state":"可用",
                "joinDate":"2017-01-01"
            },
            {
                "id":"201701",
                'index':12,
                "user":"gaohanwei1",
                "realName":"XXX",
                "section":"人力资源",
                "role":"普通管理员",
                "state":"可用",
                "joinDate":"2017-01-01"
            },
            {
                "id":"201701",
                'index':13,
                "user":"gaohanwei1",
                "realName":"XXX",
                "section":"人力",
                "role":"普通",
                "state":"可用",
                "joinDate":"2017-01-01"
            },
            {
                "id":"201",
                'index':14,
                "user":"gaohanwei1",
                "realName":"XXX",
                "section":"人力",
                "role":"普通",
                "state":"可用",
                "joinDate":"2017-01-01"
            },
            {
                "id":"201701",
                'index':15,
                "user":"gaohanwei1",
                "realName":"XXX",
                "section":"人力资源",
                "role":"普通管理员",
                "state":"可用",
                "joinDate":"2017-01-01"
            },
            {
                "id":"201701",
                'index':16,
                "user":"gaohanwei1",
                "realName":"XXX",
                "section":"人力",
                "role":"普通",
                "state":"可用",
                "joinDate":"2017-01-01"
            },
            {
                "id":"201",
                'index':17,
                "user":"gaohanwei1",
                "realName":"XXX",
                "section":"人力",
                "role":"普通",
                "state":"可用",
                "joinDate":"2017-01-01"
            },
            {
                "id":"201701",
                'index':18,
                "user":"gaohanwei1",
                "realName":"XXX",
                "section":"人力资源",
                "role":"普通管理员",
                "state":"可用",
                "joinDate":"2017-01-01"
            },
            {
                "id":"201701",
                'index':19,
                "user":"gaohanwei1",
                "realName":"XXX",
                "section":"人力",
                "role":"普通",
                "state":"可用",
                "joinDate":"2017-01-01"
            },
            {
                "id":"201",
                'index':20,
                "user":"gaohanwei1",
                "realName":"XXX",
                "section":"人力",
                "role":"普通",
                "state":"可用",
                "joinDate":"2017-01-01"
            }
        ],
        //添加账号
        addAccount:[],
        //检索数据
        searchAccount:[   {
            "id":"201",
            'index':20,
            "user":"gaohanwei1",
            "realName":"XXX",
            "section":"人力",
            "role":"普通",
            "state":"可用",
            "joinDate":"2017-01-01"
        }],
        //角色列表数据
        roleManagement:[
            {
                '角色ID':'001',
                '角色名称':'超级管理员',
                '基本权限':'查看所有页面',
                '操作权限':'编辑，发布预览，保存，删除，推送，还原，添加人员，添加角色，添加权限等',
                '创建时间':'2017-10-10'
            },
            {
                '角色ID':'002',
                '角色名称':'普通管理员',
                '基本权限':'此处为普通管理的权限',
                '操作权限':'编辑，保存，删除等',
                '创建时间':'2017-10-10'
            },
            {
                '角色ID':'003',
                '角色名称':'一级员工',
                '基本权限':'一级管理权限',
                '操作权限':'推送，还原，添加人员，添加角色，添加权限等',
                '创建时间':'2017-10-10'
            },
            {
                '角色ID':'004',
                '角色名称':'实习生',
                '基本权限':'实习生权限',
                '操作权限':'编辑，发布预览等',
                '创建时间':'2017-10-10'
            }
        ],
        //图书主数据
        books:[]
    }
}
